export const ACCOUNT_REGISTER_REQUEST = "ACCOUNT_REGISTER_REQUEST";
export const ACCOUNT_REGISTER_SUCCESS = "ACCOUNT_REGISTER_SUCCESS";
export const ACCOUNT_REGISTER_FAIL = "ACCOUNT_REGISTER_FAIL";

export const ACCOUNT_SIGNIN_REQUEST = "ACCOUNT_SIGNIN_REQUEST";
export const ACCOUNT_SIGNIN_SUCCESS = "ACCOUNT_SIGNIN_SUCCESS";
export const ACCOUNT_SIGNIN_FAIL = "ACCOUNT_SIGNIN_FAIL";
export const ACCOUNT_SIGNOUT = "ACCOUNT_SIGNOUT";


export const ACCOUNT_DETAILS_REQUEST = "ACCOUNT_DETAILS_REQUEST";
export const ACCOUNT_DETAILS_SUCCESS = "ACCOUNT_DETAILS_SUCCESS";
export const ACCOUNT_DETAILS_FAIL = "ACCOUNT_DETAILS_FAIL";
export const ACCOUNT_DETAILS_RESET = "ACCOUNT_DETAILS_RESET";

export const ACCOUNT_LIST_REQUEST = "ACCOUNT_LIST_REQUEST";
export const ACCOUNT_LIST_SUCCESS = "ACCOUNT_LIST_SUCCESS";
export const ACCOUNT_LIST_FAIL = "ACCOUNT_LIST_FAIL";


export const ACCOUNT_UPDATE_PROFILE_REQUEST = "ACCOUNT_UPDATE_PROFILE_REQUEST";
export const ACCOUNT_UPDATE_PROFILE_SUCCESS = "ACCOUNT_UPDATE_PROFILE_SUCCESS";
export const ACCOUNT_UPDATE_PROFILE_FAIL = "ACCOUNT_UPDATE_PROFILE_FAIL";
export const ACCOUNT_UPDATE_PROFILE_RESET = "ACCOUNT_UPDATE_PROFILE_RESET";

export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_UPDATE_REQUEST";
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_UPDATE_SUCCESS";
export const ACCOUNT_UPDATE_FAIL = "ACCOUNT_UPDATE_FAIL";
export const ACCOUNT_UPDATE_RESET = "ACCOUNT_UPDATE_RESET";

export const ACCOUNT_DELETE_REQUEST = "ACCOUNT_DELETE_REQUEST";
export const ACCOUNT_DELETE_SUCCESS = "ACCOUNT_DELETE_SUCCESS";
export const ACCOUNT_DELETE_FAIL = "ACCOUNT_DELETE_FAIL";
export const ACCOUNT_DELETE_RESET = "ACCOUNT_DELETE_RESET";


