export const BLOG_ADD_REQUEST = "BLOG_ADD_REQUEST";
export const BLOG_ADD_SUCCESS = "BLOG_ADD_SUCCESS";
export const BLOG_ADD_FAIL = "BLOG_ADD_FAIL";
export const BLOG_ADD_RESET = "BLOG_ADD_RESET";

///////

export const POST_ADD_REQUEST = "POST_ADD_REQUEST";
export const POST_ADD_SUCCESS = "POST_ADD_SUCCESS";
export const POST_ADD_FAIL = "POST_ADD_FAIL";
export const POST_ADD_RESET = "POST_ADD_RESET";
/////////
export const BLOG_REGISTER_REQUEST = "BLOG_REGISTER_REQUEST";
export const BLOG_REGISTER_SUCCESS = "BLOG_REGISTER_SUCCESS";
export const BLOG_REGISTER_FAIL = "BLOG_REGISTER_FAIL";

export const BLOG_SIGNIN_REQUEST = "BLOG_SIGNIN_REQUEST";
export const BLOG_SIGNIN_SUCCESS = "BLOG_SIGNIN_SUCCESS";
export const BLOG_SIGNIN_FAIL = "BLOG_SIGNIN_FAIL";
export const BLOG_SIGNOUT = "BLOG_SIGNOUT";

export const BLOG_DETAILS_REQUEST = "BLOG_DETAILS_REQUEST";
export const BLOG_DETAILS_SUCCESS = "BLOG_DETAILS_SUCCESS";
export const BLOG_DETAILS_FAIL = "BLOG_DETAILS_FAIL";
export const BLOG_DETAILS_RESET = "BLOG_DETAILS_RESET";

/////////

export const POST_DETAILS_REQUEST = "POST_DETAILS_REQUEST";
export const POST_DETAILS_SUCCESS = "POST_DETAILS_SUCCESS";
export const POST_DETAILS_FAIL = "POST_DETAILS_FAIL";
export const POST_DETAILS_RESET = "POST_DETAILS_RESET";



export const BLOG_LIST_REQUEST = "BLOG_LIST_REQUEST";
export const BLOG_LIST_SUCCESS = "BLOG_LIST_SUCCESS";
export const BLOG_LIST_FAIL = "BLOG_LIST_FAIL";

export const BLOG_UPDATE_PROFILE_REQUEST = "BLOG_UPDATE_PROFILE_REQUEST";
export const BLOG_UPDATE_PROFILE_SUCCESS = "BLOG_UPDATE_PROFILE_SUCCESS";
export const BLOG_UPDATE_PROFILE_FAIL = "BLOG_UPDATE_PROFILE_FAIL";
export const BLOG_UPDATE_PROFILE_RESET = "BLOG_UPDATE_PROFILE_RESET";

export const BLOG_UPDATE_REQUEST = "BLOG_UPDATE_REQUEST";
export const BLOG_UPDATE_SUCCESS = "BLOG_UPDATE_SUCCESS";
export const BLOG_UPDATE_FAIL = "BLOG_UPDATE_FAIL";
export const BLOG_UPDATE_RESET = "BLOG_UPDATE_RESET";
/////

export const POST_UPDATE_REQUEST = "POST_UPDATE_REQUEST";
export const POST_UPDATE_SUCCESS = "POST_UPDATE_SUCCESS";
export const POST_UPDATE_FAIL = "POST_UPDATE_FAIL";
export const POST_UPDATE_RESET = "POST_UPDATE_RESET";


////////
export const BLOG_DELETE_REQUEST = "BLOG_DELETE_REQUEST";
export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_FAIL = "BLOG_DELETE_FAIL";
export const BLOG_DELETE_RESET = "BLOG_DELETE_RESET";




export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
export const POST_DELETE_RESET = "POST_DELETE_RESET";

